import yaml

with open("dim2/tests.yaml") as f:
    test_names = yaml.safe_load(f)

trace_dirs = [f"serial/dim2/{test_name}/traces" for test_name in test_names]

rule all:
    input:
        trace_dirs


for test_name in test_names:
    alias = f'{test_name}_'
    run_solver_alias = f'{alias}run_solver'
    module test_name:
        snakefile: f"serial/dim2/{test_name}/Snakefile"

    use rule * from test_name as alias*
