configfile: "dim2/tests.yaml"

# tests = config["tests"]
tests = ["HomogeneousElasticDomain"]

rule all:
    input:
        traces=expand("serial/dim2/{test_name}/traces/trace_list.txt", test_name=tests)

# for test_name in config["tests"]:
for test_name in tests:
    alias = f'{test_name}_'

    module test_name:
        snakefile: f"serial/dim2/{test_name}/Snakefile"

    use rule * from test_name as alias*
