include: "specfem2d.smk"

stations = [f"S{i:04d}" for i in range(1, 21)]
seismograms = {"BXX": ["semd", "semv", "sema"], "BXZ": ["semd", "semv", "sema"], "PRE": ["semp"]}

traces = [
    f"{current_workdir}/traces/AA.{station}.S2.{component}.{seismogram}"
    for station in stations
    for component in seismograms.keys()
    for seismogram in seismograms[component]
]


rule all:
    input:
        rules.specfem2d_move_traces.output.trace_list,
    output:
        traces=traces,
    localrule: True
