# tests = config["tests"]
db_dirs = [d for d in os.listdir("dim2") if os.path.isdir(os.path.join("dim2", d))]

rule all:
    input:
        expand("dim2/{db_name}/database.bin", db_name=db_dirs)

# for test_name in config["tests"]:
for db_name in db_dirs:
    alias = f'{db_name}_'

    module:
        name: db_name
        snakefile: f"dim2/{db_name}/Snakefile"
        pathvars:
            cwd=f"dim2/{db_name}"

    use rule * from db_name as alias*

rule clean:
    shell:
        """
        rm -rf dim2/*/database.bin
        """
