include: "../../../meshfem2d.smk"


rule all:
    input:
        trace_list="<cwd>/traces/trace_list.txt",
        database="<cwd>/database.bin",
    localrule: True


rule link_traces:
    input:
        trace_list="<cwd>/traces_fd/trace_list.txt",
    output:
        trace_list="<cwd>/traces/trace_list.txt",
    localrule: True,
    shell:
        """
        mkdir -p $(dirname {output.trace_list})
        cd $(dirname {output.trace_list})
        ln -s ../traces_fd/* .
        """


rule clean:
    localrule: True,
    shell:
        """
        rm -rf traces
        rm -f database.bin
        """
